### ISSUE TITLE
How to disable ZIP entry ? And how to customize input card entry ?

### ISSUE THREAD

**Issue by videotape** [dbachelder/CreditCardEntry#1]
Hi ! I wanted to know if there is a possibility to disable the zip entry of the card entry ?
And is there a possibility to customize input, such as background, input borders... ?
Thanks ;)

**Comment by danieljonker** [comment]
You can just delete it and all references, then change the isCreditCardValid method to not include it

**Comment by dbachelder** [comment]
You can now use the xml attr `app:include_zip="false"` to disable zip code entry
