### ISSUE TITLE
Textcolor is not consistant

### ISSUE THREAD

**Issue by mohsin-sayyed** [dbachelder/CreditCardEntry#12]
Text color of textbox not showing black first time

**Comment by dbachelder** [comment]
Hi Mohsin, can you post a screenshot or something? I'm not sure what you mean.

**Comment by mohsin-sayyed** [comment]
My default textcolor is white. While validating Credit card number text color changes to red & turns to black. I think some where u have hardcoed textcolor to black.

**Comment by mbmc** [comment]
Should be fixed in v1.4.0

**Comment by dbachelder** [comment]
Oh cool. thanks mbmc!
