### ISSUE TITLE
This project could not be access

### ISSUE THREAD

**Issue by amila-rangana** [dbachelder/CreditCardEntry#17]
When I added this paths to my gradle file it will show error message telling "Failed to resolve:com.github.dbachelder:CreditCardEntry:v1.3.0" like that.

**Comment by dbachelder** [comment]
Did you add the repository?

`maven { url "https://jitpack.io" }`

**Comment by amila-rangana** [comment]
Yes, I added it also under
repositories{
       .......
       maven { url "https://jitpack.io" }
}

But it gave that issue. What can be the issue..?

**Comment by dbachelder** [comment]
No idea... You'll need to post your entire `build.gradle`

**Comment by dbachelder** [comment]
@amila-rangana also I just released a new version. so try `com.github.dbachelder:CreditCardEntry:1.4.0`

**Comment by amila-rangana** [comment]
Hi dan,

Now it is working great. Thank you very much. But extra attributes like

app:helper_text_color="@color/yellow_500"

is not working, then I have added

xmlns:app="http://schemas.android.com/apk/res-auto"

into root element. But it is also giving error like

Error:(9) No resource identifier found for attribute
'helper_text_color' in package 'com.devmarvel.creditcardentry'
Error:(9) No resource identifier found for attribute 'include_helper'
in package 'com.devmarvel.creditcardentry'
Error:(9) No resource identifier found for attribute 'include_zip' in
package 'com.devmarvel.creditcardentry'
Error:(15, 32) No resource found that matches the given name (at
'helper_text_color' with value '@color/yellow_500').

what should I do for that?

Regards,
Amila

---

Amila Rangana
Software Engineer
PHIZUU

Mobile   : +94 718310108
Office   : +94 117548675
Email    : rangana@phizuu.com
Web      : http://www.phizuu.com

**Comment by dbachelder** [comment]
@amila-rangana Hmm, that's fishy.. can you run the demo app?

**Comment by amila-rangana** [comment]
Hi dan,

I could figured it out correctly with your latest release. It is working
perfectly. Thank you very much.

Regards,
Amila

---

Amila Rangana
Software Engineer
PHIZUU

Mobile   : +94 718310108
Office   : +94 117548675
Email    : rangana@phizuu.com
Web      : http://www.phizuu.com
