### ISSUE TITLE
The cursor will move to the credit card number after finish enter credit card number, exp date and sec code.

### ISSUE THREAD

**Issue by zzMOM** [dbachelder/CreditCardEntry#23]
I set the credit card form including three field: number, exp date and security code.
Finish entering these three field, the cursor will move to last digit of credit card number.

**Comment by dbachelder** [comment]
I'm not sure I understand.. this does not happen in the demo app, are you sure you are not requesting focus for the CC# field in your code?

**Comment by zzMOM** [comment]
I am sorry I may decribe clearly.
After typing all three fields, the cursor lost, and the view moved to the credit card number field. It happened on some Samsung device. 
And I attached a picture of this happened on Nenux-5, after typing security code.
![nexus-5-credit-card-oddity](https://cloud.githubusercontent.com/assets/4074668/9413707/76f01a6c-47e8-11e5-8760-3c9a19ddc0ad.png)

**Comment by dbachelder** [comment]
Hmm.. can you share your code or a demo project that reproduces the issue?

**Comment by dbachelder** [comment]
If you can reproduce and provide steps, please reopen.
