### ISSUE TITLE
isCreditCardValid returns true after editing number to be incorrect

### ISSUE THREAD

**Issue by mhousser** [dbachelder/CreditCardEntry#32]
After the form is correctly filled out, and `isCreditCardValid` correctly returns `true`, I'm able to click on the credit card number, erase a bunch of the numbers (thus rendering the number incorrect), focus on some other field on the screen, and have `isCreditCardValid` still return `true` (when, in fact, I had expected it to return `false`).

I'm working with Stripe, which went on to fail because the data in the `CreditCardForm` was actually invalid at that point.

**Comment by dbachelder** [comment]
good catch. fixed in 1.4.6
