### ISSUE TITLE
Weird layout issues? margin/padding

### ISSUE THREAD

**Issue by MiralDesai** [dbachelder/CreditCardEntry#33]
Have you noticed that when using this library that the field to enter the details has a weird margin/padding around it?

I want to be able to put another EditText right below this view with no spaces and it won't let me. It has a padding/margin somewhere that is sticks too. 

I can't seem to find anywhere in the code to change this, do you know where I can change it in the library? 

It looks very weird, because this view sits at the top of my layout, then there's a gap and all my other EditTexts are below that gap, but that are sitting close to each other with no margins or padding.

**Comment by MiralDesai** [comment]
In developer options when I enable "show layout bounds" it looks like your library has some empty views right below it which create the space. Maybe a bug?

**Comment by dbachelder** [comment]
That's where the "helper text" goes. You can disable it: `app:include_helper="false"`

**Comment by MiralDesai** [comment]
Thanks, will look into this.
