### ISSUE TITLE
Weird issue with the UI element

### ISSUE THREAD

**Issue by hatpick** [dbachelder/CreditCardEntry#43]
I have CreditCardForm in my xml and it shows up in the view, but when I tap it nothing happens, no soft keyboard or anything.

```
<com.devmarvel.creditcardentry.library.CreditCardForm
            android:layout_marginLeft="@dimen/pad4"
            android:layout_marginRight="@dimen/pad4"
            android:layout_marginTop="@dimen/pad8"
            android:layout_marginBottom="@dimen/pad8"
            android:id="@+id/cc_input"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            app:include_exp="false"
            app:include_helper="false"
            app:include_security="false"
            app:include_zip="false"/>
```

Any idea what might be the issue?
p.s: it's inside a recyclerview.

**Comment by dbachelder** [comment]
Is focus being stolen by another click listener? i.e. does it work outside your recyclerview?

**Comment by hatpick** [comment]
No, there are no other listeners. I did not try it out of the recyclerview but once I added a container around it, it started working. Thank you, great library.
