### ISSUE TITLE
New Mastercard BIN range

### ISSUE THREAD

**Issue by nicopasso** [dbachelder/CreditCardEntry#47]
MasterCard has announced that they will add a new 2 series BIN range effective October 2016. The BIN range (222100-272099) will be processed with and in the same manner as the existing 51-55 BIN range (510000-559999).

https://www.forte.net/blog/mastercard-bin-range-coming/

@dbachelder 
I think it would be nice to add this new range to this great project. What do you guys think?

**Comment by WingedToaster** [comment]
yes, please
